/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controladores.ControladorCliente;
import controladores.controladorProducto;
import entidades.Cliente;
import entidades.Productos;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cardel
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField_Factura_Cliente_Id = new javax.swing.JTextField();
        mensajesBusquedaClientesFactura = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_Factura_Producto_Nombre = new javax.swing.JTextField();
        jTextField_Factura_Producto_Descripcion = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaDeFacturaProducto = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonAgregarNuevoCliente = new javax.swing.JButton();
        nombreNuevoCliente = new javax.swing.JTextField();
        identificacionNuevoCliente = new javax.swing.JTextField();
        DireccionNuevoCliente = new javax.swing.JTextField();
        telefonoNuevoCliente = new javax.swing.JTextField();
        montoPrestamoNuevoCliente = new javax.swing.JTextField();
        celularNuevoCliente = new javax.swing.JTextField();
        tipoIdentificacionCliente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDeClientes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreClienteBusqueda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        identificacionClienteBusqueda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BotonBuscarCliente = new javax.swing.JButton();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField_Producto_Con_Nombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_Producto_Con_Descripcion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField_Producto_Con_Unidades = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDeProductos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField_Producto_CP_nombre = new javax.swing.JTextField();
        jTextField_Producto_CP_descripcion = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jTextField_Producto_CP_unidades = new javax.swing.JTextField();
        jTextField_Producto_CP_precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_Producto_CP_Mensaje = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido al aplicativo del Mini-market <Nombre>");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Buscar Factura", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("Cliente");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel25.setText("Nombre");

        jLabel26.setText("Identificación");

        jTextField_Factura_Cliente_Id.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mensajesBusquedaClientesFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Factura_Cliente_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Factura_Cliente_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensajesBusquedaClientesFactura)
                .addGap(71, 71, 71))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Producto");

        jLabel27.setText("Nombre");

        jLabel28.setText("Descripcion");

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Factura_Producto_Nombre)
                            .addComponent(jTextField_Factura_Producto_Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(jButton4)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField_Factura_Producto_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jTextField_Factura_Producto_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TablaDeFacturaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Identificación", "Nombre", "Descripcion", "Unidades", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDeFacturaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeFacturaProductoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaDeFacturaProducto);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear Factura", jPanel7);

        jTabbedPane1.addTab("Facturas", jTabbedPane2);

        jLabel2.setText("Nombre");

        jLabel3.setText("Teléfono");

        jLabel4.setText("Identificación");

        jLabel5.setText("Celular");

        jLabel6.setText("Dirección");

        jLabel7.setText("Monto a prestar");

        botonAgregarNuevoCliente.setText("Crear cliente");
        botonAgregarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarNuevoClienteActionPerformed(evt);
            }
        });

        nombreNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreNuevoClienteActionPerformed(evt);
            }
        });

        tipoIdentificacionCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CC", "TI", "NIT", "Otro" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Agregar clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(montoPrestamoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DireccionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tipoIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(identificacionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(celularNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(telefonoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAgregarNuevoCliente)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nombreNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(identificacionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoIdentificacionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DireccionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(montoPrestamoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(botonAgregarNuevoCliente)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Crear clientes", jPanel1);

        TablaDeClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre", "Monto prestado", "Editar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDeClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDeClientes);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Consultar y editar clientes");

        jLabel10.setText("Nombre");

        jLabel11.setText("Identificación");

        jLabel12.setText("Usted puede buscar los clientes por nombre o su identificación");

        jLabel13.setText("si no especifica nombre ni identificación se muestran todos los clientes");

        BotonBuscarCliente.setText("Buscar");
        BotonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(identificacionClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(59, 59, 59)
                                        .addComponent(nombreClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(BotonBuscarCliente))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel9)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nombreClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(identificacionClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscarCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Consultar clientes", jPanel2);

        jTabbedPane1.addTab("Clientes", jTabbedPane3);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Nombre");

        jLabel20.setText("Descripcion");

        jLabel21.setText("Unidades");

        jLabel22.setText("Precio");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28)
                                .addComponent(jTextField_Producto_Con_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Producto_Con_Descripcion)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Producto_Con_Unidades)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField_Producto_Con_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField_Producto_Con_Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_Producto_Con_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablaDeProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Identificación", "Nombre", "Descripcion", "Unidades", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDeProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDeProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane7.addTab("Consultar Producto", jPanel3);

        jLabel14.setText("NUEVO PRODUCTO");

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel15.setText("NOMBRE");

        jLabel16.setText("DESCRIPCION");

        jLabel17.setText("UNIDADES");

        jLabel18.setText("PRECIO");

        jTextField_Producto_CP_unidades.setEditable(false);
        jTextField_Producto_CP_unidades.setText("1");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Producto_CP_nombre)
                            .addComponent(jTextField_Producto_CP_descripcion)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextField_Producto_CP_unidades)
                                .addGap(18, 18, 18)
                                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Producto_CP_precio)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_Producto_CP_Mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_Producto_CP_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_Producto_CP_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Producto_CP_unidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_Producto_CP_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Producto_CP_Mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Nuevo Producto", jPanel4);

        jTabbedPane1.addTab("Productos", jTabbedPane7);
        jTabbedPane1.addTab("Reportes", jTabbedPane5);
        jTabbedPane1.addTab("Administración", jTabbedPane6);
        jTabbedPane1.addTab("Elimnar tab", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarClienteActionPerformed
        // TODO add your handling code here:
        String nombreCliente = nombreClienteBusqueda.getText();
        String identificacionCliente = identificacionClienteBusqueda.getText();
        int identificacionClienteInt = 0;
        try {
            if (!identificacionCliente.equals("")) {
                identificacionClienteInt = Integer.parseInt(identificacionCliente);
            }

            ControladorCliente controladorCliente = new ControladorCliente();

            ArrayList<Cliente> listaDeClientes = controladorCliente.obtenerClientes(nombreCliente, identificacionClienteInt);

            //Agregar filas
            DefaultTableModel modelo = (DefaultTableModel) TablaDeClientes.getModel();

            for (int i = 0; i < modelo.getRowCount(); i++) {
                modelo.removeRow(i);
            }
            modelo.setRowCount(0);
            for (int i = 0; i < listaDeClientes.size(); i++) {
                Cliente cliente = listaDeClientes.get(i);
                Object[] fila = new Object[4];
                fila[0] = cliente.getCliente_id();
                fila[1] = cliente.getNombre();
                fila[2] = cliente.getMonto_prestamo();
                //button.setText("<HTML>Click the <FONT color=\"#000099\"><U>link "+i+"</U></FONT>"+ " to go to the Java website.</HTML>");

                fila[3] = "Editar";
                modelo.addRow(fila);

            }

            TablaDeClientes.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La identificación debe ser numérica, por favor ingrese correctamente el dato", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonBuscarClienteActionPerformed

    private void nombreNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreNuevoClienteActionPerformed

    private void botonAgregarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarNuevoClienteActionPerformed
        // TODO add your handling code here:
        String identificacionStringNuevoCliente = identificacionNuevoCliente.getText();
        String nombreEnviarNuevoCliente = nombreNuevoCliente.getText();
        String telefonoEnviarNuevoCliente = telefonoNuevoCliente.getText();
        String celularEnviarNuevoCliente = celularNuevoCliente.getText();
        String direccionEnviarNuevoCliente = DireccionNuevoCliente.getText();
        String montoAPrestarEnviarNuevoCliente = montoPrestamoNuevoCliente.getText();
        String tipoIdentificacionNuevoCliente = (String) tipoIdentificacionCliente.getSelectedItem();

        try {

            int identificacionIntNuevoCliente = Integer.parseInt(identificacionStringNuevoCliente);
            double montoAPrestarEnviarIntNuevoCliente = Double.parseDouble(montoAPrestarEnviarNuevoCliente);
            ControladorCliente controladorCliente = new ControladorCliente();
            controladorCliente.agregarCliente(identificacionIntNuevoCliente, tipoIdentificacionNuevoCliente, nombreEnviarNuevoCliente, telefonoEnviarNuevoCliente, celularEnviarNuevoCliente, direccionEnviarNuevoCliente, montoAPrestarEnviarIntNuevoCliente);

            JOptionPane.showMessageDialog(null, "Cliente creado exitosamente");
            identificacionNuevoCliente.setText("");
            nombreNuevoCliente.setText("");
            telefonoNuevoCliente.setText("");
            celularNuevoCliente.setText("");
            DireccionNuevoCliente.setText("");
            montoPrestamoNuevoCliente.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La identificación y el monto deben ser numéricos, por favor ingrese correctamente los datos", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_botonAgregarNuevoClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = jTextField_Producto_CP_nombre.getText();
        String descripcion = jTextField_Producto_CP_descripcion.getText();
        String unidades = jTextField_Producto_CP_unidades.getText();
        String precio = jTextField_Producto_CP_precio.getText();
        if (nombre.equals("") || descripcion.equals("") || unidades.equals("") || precio.equals("")) {
            jLabel_Producto_CP_Mensaje.setForeground(Color.red);
            jLabel_Producto_CP_Mensaje.setText("No dejar campos vacios");
        } else {
            try {
                Double.parseDouble(precio);

            } catch (NumberFormatException nfe) {
                jLabel_Producto_CP_Mensaje.setForeground(Color.red);
                jLabel_Producto_CP_Mensaje.setText("Precio debe ser un Numero");
                return;
            }
            jLabel_Producto_CP_Mensaje.setForeground(Color.blue);
            jLabel_Producto_CP_Mensaje.setText("CreaciÃ³n exitosa");
            String[] value = {nombre, descripcion, unidades, precio};
            controladorProducto cp = new controladorProducto();
            cp.insertProduct(value);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TablaDeClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeClientesMouseClicked
        // TODO add your handling code here:
        int fila = TablaDeClientes.getSelectedRow();
        int identificacion = (int) TablaDeClientes.getValueAt(fila, 0);

        final ControladorCliente controladorCliente = new ControladorCliente();
        ArrayList<Cliente> listaClientes = controladorCliente.obtenerClientes("", identificacion);
        final Cliente clienteActual = listaClientes.get(0);

        final JDialog dialogoEditar = new JDialog(this);

        dialogoEditar.setTitle("Editar clientes");
        dialogoEditar.setSize(600, 310);
        dialogoEditar.setResizable(false);

        JPanel panelDialogo = new JPanel();

        panelDialogo.setLayout(new GridBagLayout());

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel editarTextoPrincipalDialogo = new JLabel("Editar clientes");
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 4;
        c.insets = new Insets(15, 200, 40, 0);
        c.ipadx = 100;
        Font textoGrande = new Font("Arial", 1, 18);
        editarTextoPrincipalDialogo.setFont(textoGrande);
        panelDialogo.add(editarTextoPrincipalDialogo, c);

        c.insets = new Insets(0, 5, 10, 0);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 40;
        JLabel editarNombreClienteDialogo = new JLabel("Nombre:");
        panelDialogo.add(editarNombreClienteDialogo, c);

        c.gridx = 1;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);
        final JTextField valorEditarNombreClienteDialogo = new JTextField();
        valorEditarNombreClienteDialogo.setText(clienteActual.getNombre());
        panelDialogo.add(valorEditarNombreClienteDialogo, c);

        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 5, 10, 0);
        JLabel editarCelularClienteDialogo = new JLabel("Celular:");
        panelDialogo.add(editarCelularClienteDialogo, c);

        c.gridx = 1;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);

        final JTextField valorEditarCelularClienteDialogo = new JTextField();
        valorEditarCelularClienteDialogo.setText(clienteActual.getNumero_celular());
        panelDialogo.add(valorEditarCelularClienteDialogo, c);
        c.gridx = 2;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 5, 10, 0);
        JLabel editarMontoClienteDialogo = new JLabel("Monto a prestar:");
        panelDialogo.add(editarMontoClienteDialogo, c);

        c.gridx = 3;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);
        final JTextField valorEditarMontoClienteDialogo = new JTextField();
        valorEditarMontoClienteDialogo.setText(String.valueOf(clienteActual.getMonto_prestamo()));
        panelDialogo.add(valorEditarMontoClienteDialogo, c);

        c.gridx = 2;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 15, 10, 0);
        JLabel editarTelefonoClienteDialogo = new JLabel("Telefono:");
        panelDialogo.add(editarTelefonoClienteDialogo, c);

        c.gridx = 3;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 0, 10, 0);
        final JTextField valorEditarTelefonoClienteDialogo = new JTextField();
        valorEditarTelefonoClienteDialogo.setText(clienteActual.getNumero_telefono());
        panelDialogo.add(valorEditarTelefonoClienteDialogo, c);

        c.gridx = 0;
        c.gridy = 3;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 0, 10, 0);

        JLabel editarAddressClienteDialogo = new JLabel("Dirección:");
        panelDialogo.add(editarAddressClienteDialogo, c);

        c.gridx = 1;
        c.gridy = 3;
        c.gridwidth = 3;
        c.ipadx = 400;
        c.insets = new Insets(0, 15, 10, 0);
        final JTextField valorEditarAddressClienteDialogo = new JTextField();
        valorEditarAddressClienteDialogo.setText(clienteActual.getDireccion());
        panelDialogo.add(valorEditarAddressClienteDialogo, c);

        c.gridx = 0;
        c.gridy = 4;
        c.gridwidth = 2;
        c.ipadx = 100;
        c.insets = new Insets(15, 40, 0, 0);
        JButton botonGuardarClienteDialogo = new JButton("Guardar");
        panelDialogo.add(botonGuardarClienteDialogo, c);

        c.gridx = 2;
        c.gridy = 4;
        c.gridwidth = 2;
        c.insets = new Insets(15, 40, 0, 0);
        c.ipadx = 100;

        JButton botonCerrarClienteDialogo = new JButton("Cancelar");
        panelDialogo.add(botonCerrarClienteDialogo, c);

        dialogoEditar.add(panelDialogo);

        botonCerrarClienteDialogo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoEditar.dispose();
            }
        });

        botonGuardarClienteDialogo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    clienteActual.setDireccion(valorEditarAddressClienteDialogo.getText());
                    clienteActual.setMonto_prestamo(Double.parseDouble(valorEditarMontoClienteDialogo.getText()));
                    clienteActual.setNombre(valorEditarNombreClienteDialogo.getText());
                    clienteActual.setNumero_celular(valorEditarCelularClienteDialogo.getText());
                    clienteActual.setNumero_telefono(valorEditarTelefonoClienteDialogo.getText());

                    controladorCliente.editarCliente(clienteActual);
                    JOptionPane.showMessageDialog(dialogoEditar, "Se ha editado el cliente éxitosamente");
                    dialogoEditar.dispose();

                    //Refrescar busqueda actual
                    String nombreCliente = nombreClienteBusqueda.getText();

                    int identificacionClienteInt = 0;

                    ControladorCliente controladorCliente = new ControladorCliente();

                    ArrayList<Cliente> listaDeClientes = controladorCliente.obtenerClientes(nombreCliente, identificacionClienteInt);

                    //Agregar filas
                    DefaultTableModel modelo = (DefaultTableModel) TablaDeClientes.getModel();

                    for (int i = 0; i < modelo.getRowCount(); i++) {
                        modelo.removeRow(i);
                    }
                    modelo.setRowCount(0);
                    for (int i = 0; i < listaDeClientes.size(); i++) {
                        Cliente cliente = listaDeClientes.get(i);
                        Object[] fila = new Object[4];
                        fila[0] = cliente.getCliente_id();
                        fila[1] = cliente.getNombre();
                        fila[2] = cliente.getMonto_prestamo();
                        //button.setText("<HTML>Click the <FONT color=\"#000099\"><U>link "+i+"</U></FONT>"+ " to go to the Java website.</HTML>");

                        fila[3] = "Editar";
                        modelo.addRow(fila);

                    }

                    TablaDeClientes.setModel(modelo);

                } catch (Exception event) {

                    JOptionPane.showMessageDialog(dialogoEditar, "El valor del monto debe ser numérico");

                }

            }
        });

        dialogoEditar.setVisible(true);
        /*Action mostrarMensaje;
         mostrarMensaje = new AbstractAction() {
         @Override
         public void actionPerformed(ActionEvent e) {
         JTable table = (JTable) e.getSource();
         int modelRow = Integer.valueOf(e.getActionCommand());
         ((DefaultTableModel) table.getModel()).removeRow(modelRow);
         }
         };
         ButtonColumn buttonColumn = new ButtonColumn(TablaDeClientes, mostrarMensaje, 3);
         buttonColumn.setMnemonic(KeyEvent.VK_E);*/
    }//GEN-LAST:event_TablaDeClientesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = jTextField_Producto_Con_Nombre.getText();
        String descripcion = jTextField_Producto_Con_Descripcion.getText();
        String unidades_string = jTextField_Producto_Con_Unidades.getText();
        String precio_string = jTextField4.getText();

        int unidades = 0;
        double precio = 0;
        try {
            if (!unidades_string.equals("")) {
                unidades = Integer.parseInt(unidades_string);
            }
            if (!precio_string.equals("")) {
                precio = Double.parseDouble(precio_string);
            }

            controladorProducto controladorPro = new controladorProducto();
            String restriccion = "";

            boolean encounter = true;

            if (!nombre.equals("")) {
                if (encounter) {
                    encounter = false;
                    restriccion = " where ";
                } else {
                    restriccion += " OR ";
                }

                restriccion += " nombre like '%" + nombre + "%'";
            }

            if (!descripcion.equals("")) {
                if (encounter) {
                    encounter = false;
                    restriccion = " where ";
                } else {
                    restriccion += " OR ";
                }

                restriccion += " descripcion like '%" + descripcion + "%'";
            }

            if (!unidades_string.equals("")) {
                if (encounter) {
                    encounter = false;
                    restriccion = " where ";
                } else {
                    restriccion += " OR ";
                }

                restriccion += " unidades =" + unidades;
            }

            if (!precio_string.equals("")) {
                if (encounter) {
                    encounter = false;
                    restriccion = " where ";
                } else {
                    restriccion += " OR ";
                }

                restriccion += " precio =" + precio;
            }

            ArrayList<Productos> listaDeProductos = controladorPro.getProducto(restriccion);

            //Agregar filas
            DefaultTableModel modelo = (DefaultTableModel) TablaDeProductos.getModel();

            if (modelo.getRowCount() > 0) {
                for (int i = modelo.getRowCount() - 1; i > -1; i--) {
                    modelo.removeRow(i);
                }
            }

            for (int i = 0; i < listaDeProductos.size(); i++) {
                Productos producto = listaDeProductos.get(i);
                Object[] fila = new Object[6];
                fila[0] = (i + 1);
                fila[1] = producto.getProductoId();
                fila[2] = producto.getNombre();
                fila[3] = producto.getDescripcion();
                fila[4] = producto.getUnidadesDisponibles();
                fila[5] = producto.getPrecio();
                modelo.addRow(fila);

            }

            TablaDeProductos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La identificación debe ser numérica, por favor ingrese correctamente el dato", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaDeProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeProductosMouseClicked
        // TODO add your handling code here:
        int fila = TablaDeProductos.getSelectedRow();
        final int identificacion = (int) TablaDeProductos.getValueAt(fila, 1);

        final controladorProducto controladorP = new controladorProducto();
        ArrayList<Productos> listaProductos = controladorP.getProducto(" where producto_id = "+identificacion);
        final Productos productoActual = listaProductos.get(0);

        final JDialog dialogoEditar = new JDialog(this);

        dialogoEditar.setTitle("Editar clientes");
        dialogoEditar.setSize(600, 310);
        dialogoEditar.setResizable(false);

        JPanel panelDialogo = new JPanel();

        panelDialogo.setLayout(new GridBagLayout());

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel editarTextoPrincipalDialogo = new JLabel("Editar producto");
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 4;
        c.insets = new Insets(15, 200, 40, 0);
        c.ipadx = 100;
        Font textoGrande = new Font("Arial", 1, 18);
        editarTextoPrincipalDialogo.setFont(textoGrande);
        panelDialogo.add(editarTextoPrincipalDialogo, c);

        c.insets = new Insets(0, 5, 10, 0);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 40;
        JLabel editarNombreClienteDialogo = new JLabel("Nombre:");
        panelDialogo.add(editarNombreClienteDialogo, c);

        c.gridx = 1;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);
        final JTextField valorEditarNombreClienteDialogo = new JTextField();
        valorEditarNombreClienteDialogo.setText(productoActual.getNombre());
        panelDialogo.add(valorEditarNombreClienteDialogo, c);

        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 5, 10, 0);
        JLabel editarCelularClienteDialogo = new JLabel("Descripcion:");
        panelDialogo.add(editarCelularClienteDialogo, c);

        c.gridx = 1;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);

        final JTextField valorEditarDescripcionProductoDialogo = new JTextField();
        valorEditarDescripcionProductoDialogo.setText(productoActual.getDescripcion());
        panelDialogo.add(valorEditarDescripcionProductoDialogo, c);
        c.gridx = 2;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 5, 10, 0);
        JLabel editarMontoClienteDialogo = new JLabel("Unidades");
        panelDialogo.add(editarMontoClienteDialogo, c);

        c.gridx = 3;
        c.gridy = 2;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 15, 10, 15);
        final JTextField valorEditarUnidadesProductoDialogo = new JTextField();
        valorEditarUnidadesProductoDialogo.setText(String.valueOf(productoActual.getUnidadesDisponibles()));
        panelDialogo.add(valorEditarUnidadesProductoDialogo, c);

        c.gridx = 2;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 40;
        c.insets = new Insets(0, 15, 10, 0);
        JLabel editarTelefonoClienteDialogo = new JLabel("Precio");
        panelDialogo.add(editarTelefonoClienteDialogo, c);

        c.gridx = 3;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 100;
        c.insets = new Insets(0, 0, 10, 0);
        final JTextField valorEditarPrecioProductoDialogo = new JTextField();
        valorEditarPrecioProductoDialogo.setText(productoActual.getPrecio()+"");
        panelDialogo.add(valorEditarPrecioProductoDialogo, c);

        c.gridx = 0;
        c.gridy = 4;
        c.gridwidth = 2;
        c.ipadx = 100;
        c.insets = new Insets(15, 40, 0, 0);
        JButton botonGuardarProductoDialogo = new JButton("Guardar");
        panelDialogo.add(botonGuardarProductoDialogo, c);

        c.gridx = 2;
        c.gridy = 4;
        c.gridwidth = 2;
        c.insets = new Insets(15, 40, 0, 0);
        c.ipadx = 100;

        JButton botonCerrarProductoDialogo = new JButton("Cancelar");
        panelDialogo.add(botonCerrarProductoDialogo, c);

        dialogoEditar.add(panelDialogo);

        botonCerrarProductoDialogo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dialogoEditar.dispose();
            }
        });

        botonGuardarProductoDialogo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                   
                    String [] selection = {"nombre","descripcion","unidades","precio"};
                    String [] value = {valorEditarNombreClienteDialogo.getText(),valorEditarDescripcionProductoDialogo.getText()
                    ,valorEditarUnidadesProductoDialogo.getText(),valorEditarPrecioProductoDialogo.getText()};
                    String [] type_value = {"varchar","varchar","int","double"};
                    String restriction = " where producto_id = "+identificacion;
                    controladorP.updateProduct(selection,value,type_value,restriction);
                    JOptionPane.showMessageDialog(dialogoEditar, "Se ha editado el producto éxitosamente");
                    dialogoEditar.dispose();

                    //Refrescar busqueda actual
                    jButton2ActionPerformed(null);

                } catch (Exception event) {

                    JOptionPane.showMessageDialog(dialogoEditar, "El valor del monto debe ser numérico");

                }

            }
        });

        dialogoEditar.setVisible(true);
    }//GEN-LAST:event_TablaDeProductosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String nombre = jTextField1.getText();
        String identificacion = jTextField2.getText();
        
        System.out.println(nombre + " - " + identificacion);
        
        ControladorCliente controladorCliente = new ControladorCliente();
        int id = 0;
        if(!identificacion.equals(""))
        {         
            mensajesBusquedaClientesFactura.setText("La identificacion debe ser un numero");
            return; 
        }
        
        ArrayList<Cliente> listaClientes = controladorCliente.obtenerClientes(nombre, id);
        
        if(listaClientes.isEmpty())
        {
            mensajesBusquedaClientesFactura.setText("La busqueda no arrojo resultados");
            return;
        }
        
        final JDialog dialogoEditar = new JDialog(this);
        dialogoEditar.setTitle("Buscar clientes");
        dialogoEditar.setSize(600, 310);
        dialogoEditar.setResizable(false);

        JPanel panelDialogo = new JPanel();

        panelDialogo.setLayout(new GridBagLayout());

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel editarTextoPrincipalDialogo = new JLabel("Buscar Cliente");
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 4;
        c.insets = new Insets(15, 200, 40, 0);
        c.ipadx = 100;
        Font textoGrande = new Font("Arial", 1, 18);
        editarTextoPrincipalDialogo.setFont(textoGrande);
        panelDialogo.add(editarTextoPrincipalDialogo, c);
        
        Vector col = new Vector();
        col.add("1");
        col.add("2");
        col.add("3");
        col.add("4");
        col.add("5");
        Vector row = new Vector(); 
            
        for(int i = 0 ; i < listaClientes.size();i++)
        {
            Cliente cliente = listaClientes.get(i);
            Vector temp = new Vector();
            temp.add( (i+1)+"" );  
            temp.add( cliente.getNombre());
            temp.add(cliente.getTipo_cliente_id()+"");
            temp.add(cliente.getCliente_id()+"");
            temp.add(cliente.getMonto_prestamo()+"");
            System.out.println("info"+cliente.getNombre()+","+cliente.getMonto_prestamo());
            row.add(temp);
        }
        
        final JTable table = new JTable( row, col );
        
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                jTextField_Factura_Cliente_Id.setText(table.getValueAt(table.getSelectedRow(), 3).toString());
                //System.out.println(table.getValueAt(table.getSelectedRow(), 3).toString());
                dialogoEditar.dispose();
             }
        });
        
        
        c.insets = new Insets(0, 5, 10, 0);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 200;
        
        panelDialogo.add(table, c);
        dialogoEditar.add(panelDialogo);
        dialogoEditar.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TablaDeFacturaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeFacturaProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDeFacturaProductoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = jTextField_Factura_Producto_Nombre.getText();
        String descripcion = jTextField_Factura_Producto_Descripcion.getText();
        controladorProducto controladorPro = new controladorProducto();
        String restriccion = "";

        boolean encounter = true;

        if (!nombre.equals("")) {
            if (encounter) {
                encounter = false;
                restriccion = " where ";
            } else {
                restriccion += " OR ";
            }

            restriccion += " nombre like '%" + nombre + "%'";
        }

        if (!descripcion.equals("")) {
            if (encounter) {
                encounter = false;
                restriccion = " where ";
            } else {
                restriccion += " OR ";
            }

            restriccion += " descripcion like '%" + descripcion + "%'";
        }

        ArrayList<Productos> listaDeProductos = controladorPro.getProducto(restriccion);

        final JDialog dialogoEditar = new JDialog(this);
        dialogoEditar.setTitle("Buscar clientes");
        dialogoEditar.setSize(600, 310);
        dialogoEditar.setResizable(false);

        JPanel panelDialogo = new JPanel();

        panelDialogo.setLayout(new GridBagLayout());

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;

        JLabel editarTextoPrincipalDialogo = new JLabel("Buscar Producto");
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 4;
        c.insets = new Insets(15, 200, 40, 0);
        c.ipadx = 100;
        Font textoGrande = new Font("Arial", 1, 18);
        editarTextoPrincipalDialogo.setFont(textoGrande);
        panelDialogo.add(editarTextoPrincipalDialogo, c);
        
        Vector col = new Vector();
        col.add("1");
        col.add("2");
        col.add("3");
        col.add("4");
        col.add("5");
        col.add("6");
        Vector row = new Vector(); 
            
        for(int i = 0 ; i < listaDeProductos.size();i++)
        {
            Productos producto = listaDeProductos.get(i);
            Vector temp = new Vector();
            temp.add( (i+1)+"" );
            temp.add( producto.getProductoId());
            temp.add( producto.getNombre());
            temp.add( producto.getDescripcion());
            temp.add( producto.getUnidadesDisponibles() );
            temp.add( producto.getPrecio());
            row.add(temp);
        }
        
        final JTable table = new JTable( row, col );
        
        table.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                //jTextField_Factura_Cliente_Id.setText(table.getValueAt(table.getSelectedRow(), 1).toString());
                //System.out.println(table.getValueAt(table.getSelectedRow(), 3).toString());
                DefaultTableModel modelo = (DefaultTableModel) TablaDeFacturaProducto.getModel();

                
                    Object[] fila = new Object[6];
                    
                    fila[0] = table.getValueAt(table.getSelectedRow(), 0).toString();
                    fila[1] = table.getValueAt(table.getSelectedRow(), 1).toString();
                    fila[2] = table.getValueAt(table.getSelectedRow(), 2).toString();
                    fila[3] = table.getValueAt(table.getSelectedRow(), 3).toString();
                    fila[4] = table.getValueAt(table.getSelectedRow(), 4).toString();
                    fila[5] = table.getValueAt(table.getSelectedRow(), 5).toString();
                    
                    modelo.addRow(fila);
                //modelo.getColumnName(4).
                /*TablaDeFacturaProducto.setModel(modelo);
                TablaDeFacturaProducto.getColumnClass(4). ;*/
                dialogoEditar.dispose();
             }
        });
        
        
        c.insets = new Insets(0, 5, 10, 0);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 1;
        c.ipadx = 200;
        
        panelDialogo.add(table, c);
        dialogoEditar.add(panelDialogo);
        dialogoEditar.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarCliente;
    private javax.swing.JTextField DireccionNuevoCliente;
    private javax.swing.JTable TablaDeClientes;
    private javax.swing.JTable TablaDeFacturaProducto;
    private javax.swing.JTable TablaDeProductos;
    private javax.swing.JButton botonAgregarNuevoCliente;
    private javax.swing.JTextField celularNuevoCliente;
    private javax.swing.JTextField identificacionClienteBusqueda;
    private javax.swing.JTextField identificacionNuevoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Producto_CP_Mensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField_Factura_Cliente_Id;
    private javax.swing.JTextField jTextField_Factura_Producto_Descripcion;
    private javax.swing.JTextField jTextField_Factura_Producto_Nombre;
    private javax.swing.JTextField jTextField_Producto_CP_descripcion;
    private javax.swing.JTextField jTextField_Producto_CP_nombre;
    private javax.swing.JTextField jTextField_Producto_CP_precio;
    private javax.swing.JTextField jTextField_Producto_CP_unidades;
    private javax.swing.JTextField jTextField_Producto_Con_Descripcion;
    private javax.swing.JTextField jTextField_Producto_Con_Nombre;
    private javax.swing.JTextField jTextField_Producto_Con_Unidades;
    private javax.swing.JLabel mensajesBusquedaClientesFactura;
    private javax.swing.JTextField montoPrestamoNuevoCliente;
    private javax.swing.JTextField nombreClienteBusqueda;
    private javax.swing.JTextField nombreNuevoCliente;
    private javax.swing.JTextField telefonoNuevoCliente;
    private javax.swing.JComboBox tipoIdentificacionCliente;
    // End of variables declaration//GEN-END:variables
}
